team-fusionx/CarND-Capstone

- ros/src/twist_controller/dbw_node.py
- ros/src/twist_controller/twist_controller.py
Working towards #4 
Adding the provided `YawController` for basic steering controls with a linear response to desired angular velocity. No PID control for steering correction has yet been added.
> Add basic steering controls with yaw controller

- ros/src/twist_controller/dbw_node.py
- ros/src/twist_controller/twist_controller.py
Incredibly basic throttle and brake controller.
* PID control for acceleration with handpicked P, I, D coefficients, limited by max acceleration and deceleration.
* State reset when DBW is turned off, so that accumulated state in PID controller is removed for when (if)DBW is turned back on again.
* No feed-forward yet as recommended in [previous review](https://github.com/team-fusionx/CarND-Capstone/pull/14#discussion_r172743302), but this is just a very basic implementation to get us started.
Tested locally with simulator - throttle and braking seem to work nicely! It's revealed some choppiness with steering, which will be addressed in a future PR.
> Implement basic acceleration and deceleration in DBW controller

- ros/src/waypoint_loader/waypoint_loader.py
- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/waypnt_updater.py
For testing, I added a new dynamic parameter defaulting to the second set of traffic lights (wp = 759) that can be adjusted to allow car to move again after reaching stopline.  The car deceleration just uses linear deceleration at present, and then velocity is cut to 0 when velocity goes below a threshold, and when distance is within a radius of the stopline.  nothing is done for acceleration at present. Towards Issue #6 
Next pass is to use better logic to determine when deceleration should begin, (now I am just using number of waypoints away), and to use JMT to generate velocities.  
Also need to deepcopy waypoints from base_waypoints so that velocities placed by waypoint_loader (which are maximum velocities at that waypoint) do not get overwritten.  A global maximum velocity is …
> First Pass at stopping at lights with simple deceleration

- ros/src/styx/server.py
- ros/src/waypoint_follower/src/pure_pursuit.cpp
I read that this modification helped previous teams reduce control bugs due to lag and getting backlogged messages while running on the simulator, especially in a VM.  I'm not sure if it really fixes the issues, but seems like a good change to me to disable queuing published messages.
> Disable backlog queue msgs from styx, pure pursuit

- ros/src/twist_controller/CMakeLists.txt
- ros/src/twist_controller/cfg/DynReconf.cfg
- ros/src/twist_controller/dbw_node.py
- ros/src/twist_controller/package.xml
- ros/src/twist_controller/twist_controller_mod.py
For #4 - PID control parameters are now dynamically reconfigurable. Other parameters can be added at a later date if desired.
I've verified that these changes run properly in the simulator, and I can change the characteristics of the throttle and braking profile dynamically at runtime.
> Allow dynamic reconfiguration of velocity PID control parameters

- ros/src/waypoint_follower/include/pure_pursuit_core.h
- ros/src/waypoint_follower/src/pure_pursuit_core.cpp
Implement simple brute force search for closest waypoint to current pose instead of assuming waypoint index 0 is always the closest since waypoint_updater may have slower cycle time than waypoint_follower.  This is toward issue #20.
> Waypoint Follower: Search for closest waypoint to current pose

- ros/launch/styx.launch
- ros/src/styx/bridge.py
- ros/src/styx/server.py
- ros/src/twist_controller/dbw_node.py
- ros/src/waypoint_updater/waypnt_updater.py
With timestamps set on each message, we can now analyze communication timing statistics in *rqt_graph*.
Also, disable publishing obstacle data messages because they are coming from the simulator at high frequency and are not used for anything.
> Set message timestamps for statistics, disable obstacle msg (unused)

- ros/src/twist_controller/dbw_node.py
Delete timestamps from DBW messages (dbw_mkz_msgs) because they don't have headers.  This fixes a crash when autonomous mode is activated.
> Fix timestamp (crash if autonomous mode is activated)

- ros/src/visualization/vis_node.py
Set base waypoint path to publish once and latch instead of continuously publishing to save bandwidth.  Increase waypoint resolution and clean up code.
> Visualization:  Change visualization base wp path from continuous to single latched publish 

- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/jmt.py
- ros/src/waypoint_updater/waypnt_updater.py
Re-implementation of JMT based code used to generate the bulk of acceleration and deceleration.  Re: issue #23. The logic of the profile to generate is based on conditions at the car location, and there is no logic to try to use knowledge of conditions down the road (which could change by the time we get there anyway). 
Code is in smaller slightly more manageable chunks.
There is a lot of debugging rospy.loginfo code which can be turned down to logdebug 
There may be edge cases which need to be handled, e.g. if new stoplight is < 20 m from where car is stopped, The car won't startup.
> Teeekay jmtd

- ros/src/waypoint_updater/jmt.py
- ros/src/waypoint_updater/launch/waypoint_updater.launch
- ros/src/waypoint_updater/waypnt_updater.py
added Params initial_accel, handoff_velocity, min_moving_velocity for
initial startup settings. Renamed safety factor /
smooth_factor to accel_ratio.  fixed needless regeneration of jmt after 
initial startup.  Changed JMTD default logging structure to put time before S.
Added time value in logging during maintain speed.
Added more logging of state (maintain speed and stopped).  
Added state maintainspeed. Moved a lot of logging to debug level.
Changes to search in JMTD_at and refining init_acceleration algo will wait
for tests with spline in next PR
> Fixes for waypoint_updater

- ros/src/visualization/cfg/DynReconf.cfg
- ros/src/waypoint_updater/waypnt_updater.py
Change default to disable visualization node and change JMT profile output to logdebug to help reduce processing load.
> Reduce processing load

- ros/src/tl_detector/tl_detector.py
Make parameter to easily disable TL classifier to use ground truth pass through for control testing.
> Add parameter to easily disable TL classifier for testing

- ros/src/twist_controller/cfg/DynReconf.cfg
- ros/src/twist_controller/twist_controller_mod.py
For #50 - this work adds a low pass filter to the throttle and brake actuation commands in an attempt to remove rapid actuations.
> Add low pass filter to DBW throttle and brake commands to prevent large, rapid actuations

- ros/src/twist_controller/lowpass.py
- ros/src/twist_controller/twist_controller_mod.py
Small tweaks to split throttle/brake LPF tau so that brake command response can be slower (brake torque reaction is much faster than powertrain throttle response so stronger smoothing may be needed for brake pedal command), and to initialize LPF starting from 0 instead of allowing an initial unfiltered step change on first activation when dbw_enabled turns ON.  This is toward issue #28.
> DBW: Tweaks to split throttle/brake LPF tau and initialize from 0

- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/waypnt_updater.py
As preparation for issue #26 testing the simulator churchlot site track 2, need to reduce the number of published final waypoints and set initial waypoint pointer index to start from 0.  The churchlot only has 61 total waypoints and the car starts from the middle at waypoint 26.
> Waypoint Updater: Reduce # of waypts and set init ptr back to 0

- ros/src/twist_controller/cfg/DynReconf.cfg
After testing against DBW bag data (and seeing the new DBW tutorial video), increasing the velocity proportional control constant from 0.1 to 0.3 and integral component from 0.01 to 0.1 seems prudent.
For #51
> Increase DBW velocity proportional control response

- ros/src/tl_detector/tl_detector.py
Fix occasional crash when get_closest_waypoint() might get called after pose has arrived but waypoints have not.  Rename switch parameter that disables TF classifier and uses ground truth to classify light states for more clarity.
> TL Detector: Fix occasional crash and rename classifier switch

- ros/src/twist_controller/dbw_node.py
- ros/src/twist_controller/twist_controller_mod.py
- ros/src/waypoint_updater/waypnt_updater.py
Per [slack discussion](https://carnd.slack.com/archives/G8SCYKNSZ/p1522517708000157?thread_ts=1522516602.000020&cid=G8SCYKNSZ), this adds a message flow from the waypoint updater to the DBW node to signal the intention of deceleration. This information is useful to prevent the DBW node from applying braking when it's not desired.
Simulation testing shows that this works to prevent unnecessary braking at low target speed (2.7m/s).
> DBW node accepts deceleration intention from upstream to prevent early braking

- ros/src/waypoint_follower/include/pure_pursuit_core.h
- ros/src/waypoint_follower/src/pure_pursuit_core.cpp
When testing on the simulator test lot track 2, the waypoints are very sparse and the car reaches the end of the list so to be able to turn sharply enough, the waypoint follower needs some fixes to be able to pick the correct target lookahead point.  With these fixes (and some adjustments to waypoint updater node that will be submitted in another PR), the car is able to make the sharp turn and follow the waypoints properly on the test lot track.  This is toward issue #26.
> Waypoint Follower: Fix lookahead waypoint for test lot tight turns

- ros/launch/styx_track2.launch
Add a ROS launch file to use the styx simulator track 2 that loads the test site churchlot waypoints.  This is preparation for issue #26.
> Add ROS launch file for styx simulator track 2

- ros/src/waypoint_follower/src/pure_pursuit_core.cpp
The waypoint follower pure pursuit code calculates a lateral G limit that is used to guard the target linear velocity.  However, it calculates this guard velocity by using the angular velocity omega, which can be positive or negative depending on the turning direction, and if the turning direction has negative omega, the guarded linear velocity may calculate as a negative target linear velocity which doesn't make sense.
This fix prevents the negative target linear velocity by using the absolute value of omega for the velocity guard calculations.  This is for issue #54.
> Waypoint Follower: Fix negative target velocity

- ros/src/waypoint_updater/waypnt_updater.py
Reduce /rosout load by changing JMT log output to a single message from a concatenated string.
> Waypoint Updater: Reduce /rosout load from JMT profile log

- ros/src/waypoint_updater/waypnt_updater.py
I hit a rare race condition crash I think, where get_closest_wp() was called before the KD tree object had finished building, so I think it judged that self.waypoints existed while it was still being appended and built.  Here's a quick fix, but this should be very rare.
> Waypoint Updater: Fix crash if get_closest_wp() called while wp's are appending

- ros/src/waypoint_updater/waypnt_updater.py
Add setup_speedup_jmt(), get_max_accel(), and get_speedup_time() to allow switch from decel to accel without exceeding max_jerk.  Needs some more testing, but seems to work.
> Adjust accel_rate to keep jerk below max value in decel/accel scenario

- ros/src/waypoint_updater/jmt.py
- ros/src/waypoint_updater/launch/waypoint_updater.launch
- ros/src/waypoint_updater/waypnt_updater.py
Car now stops at correct location within dyn_tl_buffer of 3.5m,
Uses jerk to calculate distance for speedup and slowdown (except initial speedup - might change this next),
calculates correct time so curves don't wobble or overshoot target velocity
reduced max_desired_jerk to 1.0
pass max_jerk into get_min_stopping_distance
change get_max_accel to return accel_rate, distance and time
pass time into setup_spedup_jmt as optional parameter
fix error in get_speedup_time
adjust so does not recalculate previously calculated waypoints on same jmt_ptr
use self.next_tl_wp_tmp in callback, so race conditions don't occur in main loop if value changes during cycle.
some cleanup of logging to use {} consistently and to properly format.
> Teeekay desired jerk slowdown

- README.md
- dbw_control.md
I've added the DBW node documentation into Github markdown in the repository itself, rather than wiki. This ensures that the documentation can be read offline, from information in the repository alone, and the documentation will travel with the git repository even if the project is moved away from Github (Bitbucket, Gitlab, gitosis, etc)
Plus, the documentation can be peer reviewed, just like code :) (Not that I expect proofreading or link checking or anything of the sort)
> Add DBW documentation

- ros/src/waypoint_updater/waypnt_updater.py
Add reset conditions in case dbw_enabled flag is turned OFF/ON during drive.  This may occur if Udacity driver sets it OFF to manually drive back to starting point and then turns it back ON to try running the test again.
> Waypoint Updater: Add reset conditions for dbw_enabled flag

- ros/src/tl_detector/launch/tl_detector.launch
- ros/src/tl_detector/launch/tl_detector_site.launch
- ros/src/tl_detector/tl_detector.py
- Change log output setting to log file instead of screen (prevents loginfo from showing up on screen, only goes to log file, but logwarn and logerr still go to screen and log file)
- Use temp variables for appending waypoints and waypoint KD trees to prevent crash from race condition of calling get_closest_waypoint() while self.waypoints is still in the process of building.
> TL Detector: Change log setting and use temp lists for appending

- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/launch/waypoint_updater.launch
- ros/src/waypoint_updater/waypnt_updater.py
Lower the decel rate for desired_jerk calcs
using a variable amount based on current acceleration
and extend the search increment to minimum of 2.0 or 2.5% of
current estimate.
> Lower decel rate in get_min_stopping_distance

- ros/src/twist_controller/twist_controller_mod.py
For issue #115, reduce brake LPF tau from 0.5 to 0.3 (to same value as throttle) to allow faster brake release to reduce delay to start accelerating from a stop.  In simulator, the time from 100 Nm brake to 0 Nm is reduced by ~0.7 sec.
> DBW: Reduce brake LPF tau for faster release

- ros/src/twist_controller/cfg/DynReconf.cfg
- ros/src/twist_controller/twist_controller_mod.py
This is for issue #117:
- Reduce throttle P gain to reduce accel overshoot seen in Udacity site result bag data
- Reduce brake P gain to smooth out decel speed control during slowdown in simulator
- Reduce brake activation threshold to start braking earlier in decel to keep closer track of target speed profile
> DBW: Tweak throttle/brake gains and decel threshold

- ros/src/twist_controller/twist_controller_mod.py
In the video of the v1.0 site test, the steering wheel has some rapid rotation at the beginning and end of the test.  Increasing the steering LPF tau can help smooth out the rate of these large rotations, while still being able to track the overall steering movements needed during the drive.
See the attached chart showing the result of the dbw_test script run on the `1150531_2018-04-12-17-02-51.bag` data, showing the original steering command with tau 0.1 vs the proposed steering with tau 0.2:
[steering_tau_retune.xlsx](https://github.com/team-fusionx/CarND-Capstone/files/1918889/steering_tau_retune.xlsx)
> DBW: Increase steering LPF tau smoothing

- ros/src/tl_detector/light_classification/tl_classifier.py
- ros/src/tl_detector/tl_detector.py
Initialize self.state_count to pass the state count threshold on the first loop so the initial TL waypoint message will be sent with the correct initial light_wp value instead of the default initialized -1 value to allow Waypoint Updater to start with the correct driving state if starting the test already close to a light.  Also, add some logging for state and state count values.
> TL Detector: Initialize state_count to pass threshold to send initial light_wp

- ros/src/tl_detector/tl_detector.py
To prevent sending an initial waypoint of -1 on initial loop, add a condition to wait until self.pose and self.waypoint_tree have also finished initializing from their callbacks so that the get_closest_waypoint() check can return the actual waypoint index for the first published message to Waypoint Updater.
> TL Detector: Add condition on main loop to wait for pose and waypoints

- ros/src/twist_controller/launch/dbw.launch
- ros/src/twist_controller/twist_controller_mod.py
Udacity testing showed that Carla needs about 700 Nm brake torque to fully stop, so manual brake torque values need to be adjusted for this.
* Increase manual brake torque amount to 700 Nm and add increase rate limit for smooth apply (tuned for ~1 sec apply in simulator).
* Adjust site test launch parameter `decel_limit` from -1 (428 Nm) -> -2 m/s^2 (857 Nm) to allow 700 Nm manual brake torque.
* Filtered full-brake release from 700 Nm takes longer, so increase filter cut-off from 10 Nm -> 50 Nm to reduce the release time to compensate.
> DBW: Increase manual brake torque to 700 Nm to stop Carla

- ros/src/visualization/rqt_multiplot_simulation.xml
- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/waypnt_updater.py
Add `self.extra_tl_stop_buffer` which is valid if `self.is_decelerating` flag is set (when car is stopped or slowing down).  This prevents the `self.next_tl_wp` from being reset to -1, if the car passes  beyond the target stopping point.
Also added in checks for delayed update of pose, and delayed waypoint_updater loop to diagnose issues with simulator.
also changed scale in rqt_multiplot for braking.
> Add buffer beyond traffic light stop target

- ros/src/twist_controller/lowpass.py
- ros/src/twist_controller/twist_controller_mod.py
Per [Slack conversation](https://carnd.slack.com/archives/G8SCYKNSZ/p1528825626000228).
This resets the DBW brake low pass filter when switching to acceleration after manual braking. This should allow the vehicle to accelerate immediately, rather than waiting for the filtered braking value to lower through the lpf for several cycles.
> DBW node resets braking LPF when going from manual braking to acceleration, to prevent slow speed up from stop.

- ros/src/tl_detector/tl_detector.py
- ros/src/twist_controller/twist_controller_mod.py
- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/launch/waypoint_updater.launch
- ros/src/waypoint_updater/waypnt_updater.py
Changed so velocity on first waypoint when starting from stopped is set to 3.0 m/s instead of 1.0 m/s.  This reduces time to get to 2.0 m/s from about 1.8 s to 1.0 s.  Jerk and acceleration values remain within limits on simulator with this change.
Creeping speed is also increased to 1.5 m/s from 1.0 m/s.
Reduced number of consecutive traffic light signal identifications from 4 to 3 to cut status change time down by 0.1 secs.
> Faster acceleration from stopped

- ros/src/tl_detector/light_classification/tl_classifier.py
- ros/src/tl_detector/tl_detector.py
- Based on classifier accuracy data from FX-v2.2 Carla site test, raise classification confidence threshold so that <70% will become UNKNOWN light state.
- Add RED->UNKNOWN transition to be allowed if car is already stopped for the red light and light state becomes unknown (possible green light).  Velocity signal smallest non-zero value in data is ~0.2 m/s so threshold to judge stopped is set to 0.3 m/s to be slightly above this.
> TL Detector: Raise classifier confidence threshold and add RED->UNKNOWN

- ros/src/twist_controller/twist_controller_mod.py
During recent site test, Carla starts with a large initial steering correction to get on the waypoints that causes the traffic light to go out of the camera image.  Increasing the steering LPF tau to 0.4 can help slow down and reduce the initial steering correction to try to keep the light in the image while still allowing enough response to track the overall turns around the lot.
> DBW: Increase steering LPF tau to 0.4 to reduce initial steer correction

- ros/src/waypoint_follower/include/pure_pursuit_core.h
During Carla site test, the test was started with the vehicle parallel and offset to the left of the waypoints.  The initial steering correction to get on the waypoints ended up pointing the car away from the light when it stopped at the stop line.  Increasing the minimum lookahead distance for the pure pursuit algorithm can reduce the amount of this initial correction because the steering will target a waypoint a little further ahead of the car.
During simulation track 2 testing with the original church lot waypoints, the initial steering correction amount is reduced from a peak of 2 deg to 0.6 deg and the car is still able to turn sharply enough to make it around the course.
During simulation track 2 with the extracted Carla test waypoints, the car is still able to turn enough to follow …
> Waypoint Follower: Increase min lookahead distance for Carla test

- ros/src/tl_detector/tl_detector.py
Added a deque to pass images into - allowing processing of maximum number of images.  Achieved 2000 of 2807 images from Run_3.1 when processed on home machine.  Deque depth is kept to 4 to reduce latency caused by using deque.
> Pass images into deque to achieve max images processed with min latency

- ros/src/tl_detector/tl_detector.py
After switching logic to process light state by `len(self.image_q)`, need to add a dummy image for the `CLASSIFY_BY_GROUND_TRUTH == True` condition so the length will be non-zero and allow ground truth pass-through processing.
> TL Detector: Add dummy image for CLASSIFY_BY_GROUND_TRUTH
