- ros/src/twist_controller/dbw_node.py
Working towards #4 
This adds a single subscriber to listen to `dbw_enabled` messages and store the boolean state associated with them. This will toggle the drive my wire system on and off during operation.
> DBW nodes subscribes to and processes dbw_enabled messages

- ros/src/waypoint_updater/waypoint_updater.py
This code publishes the next 200 waypoints to final_waypoints topic
after each message is received on the current_pose topic. For now a
dummy velocity is inserted into all the waypoints.
Completed to achieve Issue #3
> Add basic final_waypoints updating functionality

- ros/src/twist_controller/dbw_node.py
Towards #4 
Pull in the current linear velocity and target linear and angular velocities in preparation for implementing control logic.
> Input control and target velocities into DBW node

- ros/src/waypoint_updater/waypoint_updater.py
Set default settings from file if not already configured in param
server, Also set up to publish to final_waypoints at 10 Hz
(configurable) instead of each time a pose msg is received.
> Add way to retrieve variables for waypoint_updater from param server

- ros/src/waypoint_updater/waypnt_updater.py
Started branch to assign zero velocity at Traffic lights, but first added local search for closest_waypoint. Seems to work ok, guessing it runs about 99.9995% less cycles to calculate than running through whole 11,000 waypoints.
> Add local closest_waypoint search

- ros/src/visualization/CMakeLists.txt
- ros/src/visualization/cfg/DynReconf.cfg
- ros/src/visualization/launch/vis_node.launch
- ros/src/visualization/package.xml
- ros/src/visualization/vis_node.py
Switch visualization node parameters (enable flag and update rate) to use dynamic reconfigure, following method from PR #18.  This is toward issue #8.
> Visualization: Apply dynamic reconfigure params to vis_node

- ros/src/twist_controller/twist_controller.py
I've twice seen instances where the ROS loop in the DBW node does not sleep for any appreciable amount of time, causing the timestep in the `compute_acceleration` method of the twist_controller to return 0. This causes a divide by zero in the `PID` module which crashes the DBW node.
Certainly, I should add some exception handling in the main DBW ROS loop prevent catastrophes like this from occurring outside the simulator, but this one particular case can be easily fixed. I chose to return the previous computed acceleration value if a timestep is 0, to prevent any issues in the PID controller.
> DBW node handles no timestep on loop iteration

- ros/src/tl_detector/tl_detector.py
Currently using the simulator/camera image - with ground truth stop line information from stop line config - the next closest way point to the light is predicted. I am printing light state and next closest waypoint at a point- this log infor is p=for debug purpose we can comment it out later.
> Meenunat tl gt pass

- ros/src/twist_controller/cfg/DynReconf.cfg
- ros/src/twist_controller/dbw_node.py
- ros/src/twist_controller/twist_controller_mod.py
Dataspeed's description of their DBW system led to inspiration about how to plug in the acceleration low pass filter and how to handle velocity changes more gracefully.
TODO: better reset of pid controllers and improve steering
> Update DBW node with better velocity delta handling

- ros/src/waypoint_updater/waypnt_updater.py
Fix the closest_waypoint routine so it does a local search without the final_waypoints list. 
Add checks on dynamic variables in dyn_vars_cb()
> Fix local closest_waypoint search

- ros/src/tl_detector/tl_detector.py
Traffic light config ground truth data is read from yaml file and it is used to predict the upcoming light state and upcoming nearest waypoint. I have updated logging to indicate this information only once. Please let me know if this meets the requirement for #45?
Also mistakenly I deleted my old branch - but I do have it locally. My current commit is from the master which had the old files. Please do let me know should I commit the old branch for tracking purpose. Sorry about that. :(
> tl logging - Issue #45

- ros/src/twist_controller/cfg/DynReconf.cfg
- ros/src/twist_controller/twist_controller_mod.py
For #28 and #50 
This seems to track desired speed much more smoothly than the previous incarnation: both through acceleration and deceleration.
I have noticed a tiny bit of back and forth between throttle and brake with certain deceleration scenarios, but I've mostly noticed it due to simulator lag (simulator not sending up to date vehicle readings) and it's quite minimal. I certainly think the improvement is better than what is in master today.
> Improve DBW throttle and braking

- ros/src/tl_detector/tl_detector.py
Enabled ground truth data enabling always to meet #45 requirements. 
@edufford - Please review the code and let me know if any further requirements are required
> Enable Ground truth data logging always 

- ros/src/tl_detector/tl_detector.py
Reverts team-fusionx/CarND-Capstone#55
> Revert "Enable Ground truth data logging always "

- ros/src/tl_detector/tl_detector.py
Recheck-in for - Enabled ground truth data enabling always to meet #45 requirements.
@edufford - Please reapprove the changes
> Meenunat gt classifer

- ros/src/twist_controller/twist_controller_mod.py
For #28 
This applies a constant braking torque when the vehicle is decelerating and it's within 1.5m/s of 0 (per recommendation [here](https://github.com/team-fusionx/CarND-Capstone/pull/53#discussion_r1766806150)).
> Apply fixed braking torque when decelerating to a stop, and at rest.

- ros/src/tl_detector/light_classification/tl_classifier.py
- ros/src/tl_detector/tl_detector.py
Merged code changes from #60 and #58.
reduced the logging with roslogdebug.
Also tried to move the processing to a separate fixed rate loop.
> Code merge traffic light detector and classifier

- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/jmt.py
- ros/src/waypoint_updater/launch/waypoint_updater.launch
- ros/src/waypoint_updater/waypnt_updater.py
Calculates the minimum stopping distance based on not exceeding a maximum jerk value 100 ms after changing direction of acceleration. Now uses a distance in produce_slowdown.  Also cuts back on logging, but moves some state changes to WARN
> Teeekay recalculate

- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/jmt.py
- ros/src/waypoint_updater/launch/waypoint_updater.launch
- ros/src/waypoint_updater/waypnt_updater.py
Made changes to enforce maximum velocity found on track.  May be verbose when trying to set values exceeding maximum velocity.
> Teeekay max v fix

- ros/src/waypoint_updater/waypnt_updater.py
print state changes with ptr id as logwarn msg so it appears on screen.  We can see what is happening after receiving traffic msgs
> Fix state change warnings

- ros/src/tl_detector/tl_detector.py
Following example from Udacity video and waypoint_updater, implement KDTree data structure for efficient closest waypoint search.  Each search time reduces from ~10ms to <1ms.
> TL Detector: Implement KDTree closest waypoint search

- ros/src/waypoint_updater/waypnt_updater.py
Fixes local search, and deals with reaching the end of track, and not trying to speedup if waypoint set to max velocity of waypoint.
> Fix closest_waypoint local search deal with end of track issues

- ros/src/twist_controller/twist_controller_mod.py
Further method to prevent throttle bumps during slowdowns by preventing throttle apply until after filtered brake pedal has fully released.  Also adjust LPF tau value a little to balance the delays when switching between brake-throttle.  I also updated the logging a little to help see the mode and velocity error threshold for testing.
There is still an issue where after the manual braking activates, the car can stop a little before reaching the waypoint updater's last waypoint to judge stopped so the target speed remains a little above 1.0 m/s.  This prevents creeping from activating if the stopping point is moved a very small distance ahead, and also can cause a larger initial throttle apply due to the initial error from larger gap between current speed at 0.0 and target above 1.0 m/s. …
> DBW: Try modifications for avoiding slowdown throttle bump

- ros/src/twist_controller/twist_controller_mod.py
Some final tuning on DBW node to avoid small throttle usage when slowing down and at very low speed.
> Severly restrict positive throttle when slowing down and velocity is less than 5m/s

- ros/src/tl_detector/light_classification/tl_classifier.py
- ros/src/tl_detector/tl_detector.py
The Car is now able to stop on red and go on green till the end of track. 
You can download the model from below link (ResNet50-SimData-tl-weights-Best-val_acc-1.0.hdf5)
https://drive.google.com/open?id=17W_m9gsLmsUyr8u5Hd-d3Q3uWjxb9pqG
> Updated model and preprocessing step 

- ros/src/tl_detector/light_classification/tl_classifier.py
- ros/src/tl_detector/tl_detector.py
@edufford @shrikondra - Could you please review the changes.
> Updated the TL detection logic

- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/jmt.py
- ros/src/waypoint_updater/launch/waypoint_updater.launch
- ros/src/waypoint_updater/waypnt_updater.py
Add tests for track 2 and track 1
Fix state check that blocked short dist_tl update
Added some logging
Set to rospy.INFO by default
Cleanup code, remove unused functions and variables
> Add changes from teeekay_desired_jerk_slowdown PR #96

- ros/src/waypoint_updater/waypnt_updater.py
The same change was made for both get_stopping_time and get_speedup_time.  I could not (at present) find a way that can consistently tell if the search is converging/diverging since we are checking values at both ends of the curve.  A fallback was added to search in the other direction if the original search direction failed.  The search increment was also boosted to give a bigger search area with the same number of iterations.
It is still possible that the search will not go far enough in a direction before giving up.  A check was added to make sure that T was not set below maximum speed limitations.
It is also possible that some cases are not solvable. 
e.g. We could be stopping with a strong acceleration rate that makes it impossible to meet our jerk requirements to speed up again …
> Add searchback and Tmin on get_stopping_time and get_speedup_time

- ros/src/tl_detector/light_classification/models/classifier_model_readme.txt
- ros/src/tl_detector/light_classification/models/model_file_join.py
- ros/src/tl_detector/light_classification/models/model_file_split.py
- ros/src/tl_detector/light_classification/tl_classifier.py
- Remade model split files without compression using simply Python scripts.
- Split model files will be automatically rejoined if needed on first run.
- Modified some formatting for PEP8 linter.
- Set classifier logging to loginfo (currently still outputs to screen, but will change this setting in another PR)
> TL Detector: Add simple Python script to join model file if needed

- ros/src/waypoint_updater/launch/waypoint_updater.launch
Reduce max_desired_jerk to help smooth out accel profiles.
> Waypoint Updater: Reduce max_desired_jerk to 0.5 m/s^3

- README.md
We're almost ready for submission!
> Update README to remove construction image

- ros/src/tl_detector/tl_detector.py
Updated the state machine to update waypoint if the last/current state is yellow. @edufford , @shrikondra  -Please review the changes.
> TL detection: updated the condition to update wp 

- ros/src/waypoint_updater/waypnt_updater.py
Until it receives a traffic_waypoint msg, the updater will just send velocity 0.0 in waypoints, and will publish is_decelerating to signal dbw to apply brakes.
Uses self.start_check set to False at startup, and only reset in traffic_cb.  
Did not reapply with reset_for_dbw because I assumed that TF would remain operational.
Moved publish_waypoints and log_sent_waypoints into their own functions.
> Set updater to hold car in place until it receives first TL msg

- ros/src/waypoint_updater/waypnt_updater.py
recursively reduces stopping distance from original estimate.  Helps regarding issue #114
> Add recursive improve_min_stopping_distance

- ros/src/tl_detector/tl_detector.py
Update state count logic not to reset to 0 when transitioning from YELLOW to RED in tl_detector
> update state count logic

- ros/src/waypoint_updater/jmt.py
- ros/src/waypoint_updater/waypnt_updater.py
Doubles search increment after 20 iterations in improve_min_stopping_distance.  
Reduces many logwarns to loginfos.  
Adds distance information into tl and slowdown messages.
> Add progressive search in improve_min_stopping_distance.  Refine logging

- ros/src/twist_controller/twist_controller_mod.py
Apply increased manual brake torque for full stop at very low speed at site test.
> DBW: Apply increased manual brake torque for full stop at very low speed

- ros/src/waypoint_updater/cfg/DynReconf.cfg
- ros/src/waypoint_updater/waypnt_updater.py
moved stop target further back so car is behind line.  Added small offset for creeping into buffer.
> Optimize buffer values for creep and stop

- ros/src/waypoint_updater/waypnt_updater.py
Add check to see if car had just stopped at lights before moving.  If so car should not worry about yellow or red lights that have cycled really fast, and should keep rolling!
> Prevent double stop at same light

- ros/src/tl_detector/launch/tl_detector.launch
- ros/src/tl_detector/launch/tl_detector_site.launch
- ros/src/tl_detector/light_classification/models/model_file_join.py
- ros/src/tl_detector/light_classification/models/model_file_split.py
- ros/src/tl_detector/light_classification/tl_classifier.py
- ros/src/tl_detector/tl_detector.py
Improve model accuracy by zooming on lights
Tests up to 5 224x224 px clips within the middle strip of the 800x600 px image for tl classification.
uses optimized search pattern of clips to reduce number of clips searched on each image based on location of last match.
> New model based only on site images.  

- ros/src/tl_detector/light_classification/tl_classifier.py
- ros/src/tl_detector/tl_detector.py
magnify sections of clips by 1.5 to try to get a better reading if there are indications there is a Traffic Light present in a clip, but values don't conclusively tell what color light is.
Running this code slows TF detection from 0.05 to 0.09 s on test machine, but will probably run in about 0.05 s on Carla.
> Add second level of magnification to detect traffic light status

- ros/src/waypoint_updater/waypnt_updater.py
Extend stopping distance at slow speed so it is longer than default 0.5 m.
Fix logging using get_distance_to_target() when stop_target is not set
> Increase speed at which car can transition to creeping to lights
